#define _HAND_H_
#include <iostream>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <assert.h>
#include <GL/glut.h>
#include <GL/glu.h>
#include <string>
#include <vector>
